### ISSUE TITLE
macOS version requirement

### ISSUE THREAD

**Issue by b0gdanw** [mbenoukaiss/clapet#3]
Hello,
Why does the app require macOS 13? Is there a reason for not working on macOS 12 or 11?
Best regards,
Bogdan

**Comment by mbenoukaiss** [comment]
Hello, I just tried compiling the app for MacOS 12 but since I made it having 13 as the selected version there are many things incompatible with previous MacOS versions, notably the launch on login stuff. I'll try to see if I can do something.
The main reason I made this app is I couldn't get Amphetamine to work on M1/M2 macbooks (and also the automatic part), so Amphetamine should work for older versions meanwhile, just without the display detection part.

**Comment by mbenoukaiss** [comment]
I'm going to close this as I was unable to downgrade to other macos versions as I don't know much about macOS apps development, so I don't know how some things I've done in the context of a recent macos versions are supposed to be done in older versions
