### ISSUE TITLE
How to hide dock icon?

### ISSUE THREAD

**Issue by SilverMarcs** [mbenoukaiss/clapet#4]
When Clapet starts, the dock icon persists. Sometimes it does go away on its own randomly but not sure what causes that. is  it possible to completely hide dock icon while having it run in the bg?

**Comment by mbenoukaiss** [comment]
On my computer it instantly hides when the applicaiton starts, iirc how it works is macos has two modes for programs, one is they appear in dock and have windows visible, and the other is a background process mode, so no window and no dock icon.

Problem is I need to open a window when you open Clapet settings so what I do is hide the dock icon by default when you start the application and show it when you open settings because I have to (else settings window won't be visible). Could it be that you have the settings window open ?

If not can you give more info on your mac version and model ? I can try to see if there has been some API changes in the way this is handled but I'm not confident I could find a fix

**Comment by SilverMarcs** [comment]
I am on the latest ventura on M1 Pro 14 inch

From what I've seen on other apps, they have an 'overlay ' mode which is basically just the settings page that runs on top of everything else. So they can have the settings page open without having a dock icon. and of course theres no icon when the settings page is closed either. Having or not having a menubar icon has no effect.

For Clapet, one workaround I found for now is to click on the dock icon. Click Clapet>Preferences from left of menubar. and there enable check for updates which shows the menubar icon on the right in the system tray. I click on the menubar icon, click settings. And now if i close the settings page which was accessed via menubar icon, the dock icon goes away. Later if I want I can make the menubar icon to go away as well by holding command and dragging it outside.

**Comment by mbenoukaiss** [comment]
Should be fixed by the latest release https://github.com/mbenoukaiss/clapet/releases/tag/1.0.3
