### ISSUE TITLE
Clapet Grey out all functions.

### ISSUE THREAD

**Issue by UnNew90** [mbenoukaiss/clapet#9]
Hi,

I'm using macOS Sequioa Beta 8.

I found out the Clapet function cannot choose and grey out all the the functions.

Is it related to **pmset**?

I attached the screenshot for your reference

Thanks.

<img width="572" alt="SCR-20240905-mvnl" src="https://github.com/user-attachments/assets/760874ff-e849-46e4-90e1-2a8cc8b95bb6">

**Comment by mbenoukaiss** [comment]
Hello, I can not look at the code right now but IIRC when the program does not have permissions to use pmset it greys everything out because it just can't do anything to disable sleep.

You can open the settings and in the advanced tab there should be a button to automatically reconfigure pmset, let me know if it works !

**Comment by mbenoukaiss** [comment]
Oh I just noticed the settings are also greyed out, that's a bug I need to fix then.

For now you'll need to exit the app, delete the settings file which should be in ~/Library/Preferences/fr.mbenoukaiss.Clapet.plist or something similar, and restart the app, it should show an introduction screen and you can click on the button to automatically configure

**Comment by UnNew90** [comment]
> Oh I just noticed the settings are also greyed out, that's a bug I need to fix then.
> 
> For now you'll need to exit the app, delete the settings file which should be in ~/Library/Preferences/fr.mbenoukaiss.Clapet.plist or something similar, and restart the app, it should show an introduction screen and you can click on the button to automatically configure

Hi, I already deleted the plist as per suggestion. However, it still same.

you can refer to screenshot attached.

<img width="866" alt="SCR-20240905-rnzc" src="https://github.com/user-attachments/assets/128cff6e-3085-492e-9fa5-1a07d81cd83f">

**Comment by mbenoukaiss** [comment]
Sorry I did not have much time to look into it, I suspect the settings are saved somewhere else in new macOS versions since I was not able to reset my settings by deleting the file as I told you, but in previous versions it used to work this way. I'll try to see if I can fix it this week

**Comment by UnNew90** [comment]
Hi,

Thank you for your email.

Noted on that.

I will wait for next update.

Thanks for your hard work.


Best Regards,
Husaini

**Comment by Nerioth11** [comment]
Bumping this one up 👍  Seems is not working on Sonoma. Thank you for your great work!

**Comment by Lzyct** [comment]
Any update about this issue? 
Thank you

**Comment by mbenoukaiss** [comment]
Hello, sorry for the wait, I just released a fix, tested on Sonoma and everything seems to be working now (setup, and accessing settings).

If something is still wrong after the update, try to go into the settings (should not be greyed out now), and click the Reset settings button in the Advanced tab and quit the application (Cmd + Q) then try to restart the application

**Comment by UnNew90** [comment]
Hello, Thanks.

I've done do as instucted. However, on Sequioa is disabled.

You can refer to picture below.

<img width="286" alt="image" src="https://github.com/user-attachments/assets/552b268b-41ea-4c04-a3fa-d2d9464f9f05">

**Comment by mbenoukaiss** [comment]
Then I believe the issue is that permissions to use pmset are not set correctly. "Automatically handle sleep" is greyed out when the program detects it can't use pmset.

Do you get prompted with your password when closing the program or clicking the "Disable sleep" button ?

If so, you should tru going into advanced settings tab and clicking "Configure pmset, it will prompt your password to configure permissions automatically.

If you know how to use the terminal you can also do the configuration yourself (but it will do the same thing) there is a guide in the README of the repository
